#!/usr/bin/env node
'use strict';

//assumes node_modules is at root of repository

var spawn = require('child_process').spawn,
    gulp = (process.platform === 'win32' ? 'gulp.cmd' : 'gulp'),

    notifier = require('node-notifier'),
    asciiUtil = require('../../gulp-utils/ascii'),

    gulpTasks = {
        examineAll: ['lint',  'test'],
        examineOnlyModified: ['pre-commit']
    },
    gulpArgs = gulpTasks.examineAll;

//hook is a handle to the child-process we're spawning
var hook = spawn(gulp, gulpArgs, {
    stdio: 'inherit'//allows child-process to write output to current terminal session
});

hook.on('close', function (code) {
    if (code !== 0) {
        notifier.notify({
            title: 'Cannot Commit',
            message: 'Awww, it\'s a sad - Pre-Commit Check Failed :-('
        });
    } else {
        console.log('\n' + asciiUtil.thumbsUp + '\n');
    }
    process.exit(code);
});

// catch exceptions so node doesn't exit prematurely,
// leaving a runaway process
process.on('uncaughtException', function (err) {
    notifier.notify({
        title: 'Uncaught Pre-Commit Exception',
        message: err.stack
    });
    console.error('Uncaught Pre-Commit Exception', err.stack);
    //http://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html
    hook.kill('SIGTERM');
    process.exit(1);
});
